name: docker

on: push

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          sep-tags: " "
          images: robol/sharelatex
          tags: |
            type=ref,event=tag
            type=ref,event=branch
            type=semver,pattern={{version}}
      - name: Build Docker image
        run: |
          for tag in ${{ steps.meta.outputs.tags }}; do
            echo "Tag: $tag"
          done
          git clone https://github.com/robol/overleaf.git
          cd overleaf
          sed -i "6s/master/$(echo $GITHUB_REF | cut -d '/' -f3)/g" services.js
          sudo make build-community
          for tag in ${{ steps.meta.outputs.tags }}; do
            sudo docker tag robol/sharelatex $tag
          done
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}      
      - name: Push to Docker Hub
        run: |
          sudo docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}
          sudo docker push -a robol/sharelatex
